---
- name: get hostname
  shell: hostname -f
  register: hostname
- debug:
    var: hostname
- name: get hostname
  shell: cat /etc/os-release | grep NAME | cut -d '=' -f2|head -n 1| sed 's/"//g'
  register: os_name
- debug:
      var: os_name
- name: get version
  shell:  cat /etc/os-release | grep VERSION_ID | cut -d '=' -f2| sed 's/"//g'
  register: os_version
- name: copy the file remotely
  copy:
    src: static/
    dest: /opt
  delegate_to: localhost

- name: run python script
  shell: python3.7 /opt/inventory.py {{hostname.stdout}} "{{os_name.stdout}}" {{os_version.stdout}}
  delegate_to: localhost
